name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: carrick
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set database credentials
        run: echo '::set-env name=DATABASE_URL::postgres://postgres:postgres@localhost/carrick'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev --system --deploy
      - name: Run collectstatic
          run: python manage.py collecstatic --noinput
      - name: Run black
        run: black . --check
      - name: Run flake8
        run: flake8 --count --show-source --statistics
      - name: Run isort
        run: isort -c
      - name: Run bandit
        run: bandit -r . -c bandit.yml
      - name: Run system checks
        run: python manage.py check --deploy
      - name: Check migrations
        run: python manage.py makemigrations --check --dry-run --noinput
      - name: Run pytest
        run: pytest -vvv
